### ISSUE TITLE
您好，您写的太棒了！能求一份sql脚本吗？

### ISSUE THREAD

**Issue by s1dereal** [WBBB0730/Steam#2]
兄弟，能发份sql脚本吗，想学习一下您的项目

**Comment by WBBB0730** [comment]
> 兄弟，能发份sql脚本吗，想学习一下您的项目

我记得这个项目的数据表是通过实体类自动创建的，你看一下[实体类](https://github.com/WBBB0730/Steam/tree/main/BackEnd/src/main/java/com/wbbb/steam/entity)就可以了
